config/routes.rb
require "solid_queue_dashboard"
Rails.application.routes.draw do
  resources :group_classifier_states
  resources :banned_users
  resources :trained_messages do
    post :bulk_update, on: :collection
  end
  resources :tokenization_samples, only: [ :new ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "trained_messages#index"

  # Metrics endpoint for Prometheus
  get "/metrics", to: "metrics#show"

  mount SolidQueueDashboard::Engine, at: "/solid-queue"
end

app/models/trained_message.rb
class TrainedMessage < ApplicationRecord
  enum :message_type, { spam: 0, ham: 1, untrained: 2, maybe_spam: 3, maybe_ham: 4 }
  # New enum for what is being trained
  enum :training_target, { message_content: 0, user_name: 1 }
  enum :source, { chat: 0, feedspam_command: 1, import: 2 }
  enum :marked_by, { admin_dashboard: 0, group_admin: 1, auto_sync: 2, not_marked_yet: 3 }
  module MarkedBy
    GROUP_ADMIN = "group_admin"
    ADMIN_DASHBOARD = "admin_dashboard"
    AUTO_SYNC = "auto_sync"
    NOT_MARKED_YET = "not_marked_yet"
  end
  module MessageType
    SPAM = "spam"
    HAM = "ham"
    UNTRAINED = "untrained"
    # classified as spam, but need to confirm
    MAYBE_SPAM = "maybe_spam"
    MAYBE_HAM = "maybe_ham"
  end
  module TrainingTarget
    MESSAGE_CONTENT = "message_content"
    USER_NAME = "user_name"
  end
  module Source
    CHAT = "chat"
    FEEDSPAM_COMMAND = "feedspam_command"
    IMPORT = "import"
  end
  GLOBAL_SHARED_MESSAGE = 0

  scope :shared, -> { where(group_id: GLOBAL_SHARED_MESSAGE) }
  scope :trainable, -> { where(message_type: [ :spam, :ham ]) }
  scope :for_message_content, -> { where(training_target: :message_content) }
  scope :for_user_name, -> { where(training_target: :user_name) }

  validates :group_id, presence: true
  validates :message, presence: true
  validates :message_type, presence: true

  before_save :set_message_hash
  # Automatically train classifier after creating/updating a message
  after_create :retrain_classifier, if: :trainable?
  after_update :retrain_classifier, if: :trainable_type_changed?
  after_create :should_ban_user, if: :trainable?
  after_update :should_ban_user, if: :trainable_type_changed?
  after_update :sync_message_type_by_hash, if: :saved_change_to_message_type?

  def should_ban_user
    if [ GroupClassifierState::TELEGRAM_DATA_COLLECTOR_GROUP_ID, GroupClassifierState::USER_NAME_CLASSIFIER_GROUP_ID ].include? self.group_id
      Rails.logger.info "Shouldn't ban user in non-existing group"
      return
    end
    # imported trained data set from CSV
    if [ 0 ].include? self.sender_chat_id
      Rails.logger.info "Shouldn't ban non-existing user"
      return
    end

    spam_ban_threshold = Rails.application.config.spam_ban_threshold
    spam_count = TrainedMessage.where(group_id: self.group_id, sender_chat_id: self.sender_chat_id, message_type: :spam, source: :chat).count
    global_spam_count = TrainedMessage.where(sender_chat_id: self.sender_chat_id, message_type: :spam, source: :chat).count
    chat_member = TelegramMemberFetcher.get_bot_chat_member(self.group_id)
    can_ban_user = [ "administrator", "creator" ].include?(chat_member&.status) && chat_member&.can_restrict_members
    if global_spam_count >= spam_ban_threshold * 2 && can_ban_user
      Rails.logger.info "user: #{self.sender_user_name}:#{self.sender_chat_id} has sent #{global_spam_count} spam messages, ban this user globally"
      TelegramBackgroundWorkerJob.perform_later(
        action: PostAction::GLOBAL_BAN_USER,
        trained_message_data: {
          sender_user_name: self.sender_user_name,
          sender_chat_id: self.sender_chat_id,
          group_id: self.group_id,
          group_name: self.group_name,
          message: self.message,
          message_id: self.message_id
        }
      )

    elsif spam_count >= spam_ban_threshold && can_ban_user
      Rails.logger.info "user: #{self.sender_user_name}:#{self.sender_chat_id} sent more than #{spam_ban_threshold} spam messages in group: #{self.group_id}, ban this user from group"
      TelegramBackgroundWorkerJob.perform_later(
        action: PostAction::BAN_USER,
        trained_message_data: {
          sender_user_name: self.sender_user_name,
          sender_chat_id: self.sender_chat_id,
          group_id: self.group_id,
          group_name: self.group_name,
          message: self.message,
          message_id: self.message_id
        }
      )
    end
  end

  def retrain_classifier
    return if untrained?

    BatchProcessor.add_to_batch(
      "classifier_training_batch_key",
      "ClassifierTrainerJob",
      self,                     # pass trainedMessage as item_data
      {},                        # no shared_args needed
      batch_size: 500,
      batch_window: 10.minutes
    )
  end

  private

  def trainable?
    spam? || ham?
  end

  def trainable_type_changed?
    return false unless saved_change_to_message_type?

    old_type, new_type = saved_change_to_message_type
    (old_type != "untrained") || (new_type != "untrained")
  end

  def set_message_hash
    self.message_hash = Digest::SHA256.hexdigest(message.to_s)
  end

  def sync_message_type_by_hash
    if spam? || ham?
      MessageTypeSyncJob.perform_later(self.message_hash, self.message_type.to_sym)
    end
  end
end

app/controllers/trained_messages_controller.rb
class TrainedMessagesController < ApplicationController
  before_action :set_trained_message, only: %i[ show edit update destroy ]

  # GET /trained_messages or /trained_messages.json
  def index
    @trained_messages = TrainedMessage.all

    if params[:message_type].present? && params[:message_type] != "all"
      @trained_messages = @trained_messages.where(message_type: params[:message_type])
    end

    if params[:training_target].present? && params[:training_target] != "all"
      @trained_messages = @trained_messages.where(training_target: params[:training_target])
    end

    if params[:group_name].present? && params[:group_name] != "all"
      @trained_messages = @trained_messages.where(group_name: params[:group_name])
    end

    if params[:source].present? && params[:source] != "all"
      @trained_messages = @trained_messages.where(source: params[:source])
    end

    if params[:marked_by].present? && params[:marked_by] != "all"
      @trained_messages = @trained_messages.where(marked_by: params[:marked_by])
    end

    if params[:search].present?
      @trained_messages = @trained_messages.where("message LIKE ?", "%#{params[:search]}%")
    end

    # Sorting
    sort_by = params[:sort] || "updated_at"
    sort_direction = params[:direction] || "desc"
    @trained_messages = @trained_messages.order("#{sort_by} #{sort_direction}")

    # Pagination
    @per_page = (params[:per_page] || 10).to_i
    @per_page = 10 if @per_page < 1 || @per_page > 100

    @total_count = @trained_messages.count
    @page = (params[:page] || 1).to_i
    @page = 1 if @page < 1

    offset = (@page - 1) * @per_page
    @trained_messages = @trained_messages.limit(@per_page).offset(offset)

    # Calculate pagination info
    @total_pages = (@total_count.to_f / @per_page).ceil

    # Using unscoped ensures we get all possible options, not just the filtered ones.
    filter_data = TrainedMessage.unscoped.distinct.pluck(:message_type, :training_target, :group_name, :source, :marked_by)

    # Get filter options
    @message_types = filter_data.map(&:first).uniq.compact.sort
    @training_targets = filter_data.map(&:second).uniq.compact.sort
    @group_names = filter_data.map(&:third).uniq.compact.sort
    @sources = filter_data.map(&:fourth).uniq.compact.sort
    @marked_bys = filter_data.map { |data| data[4] }.uniq.compact.sort
  end

  # GET /trained_messages/1 or /trained_messages/1.json
  def show
  end

  # GET /trained_messages/new
  def new
    @trained_message = TrainedMessage.new
  end

  # GET /trained_messages/1/edit
  def edit
  end

  def bulk_update
    message_ids = params[:trained_message_ids]
    if message_ids.blank?
      redirect_to trained_messages_path(request.query_parameters), alter: "You must select at least one message."
      return
    end

    messages = TrainedMessage.where(id: message_ids)
    update_count = messages.count

    new_message_type_symbol = case params[:commit]
    when "Mark as Ham" then :ham
    when "Mark as Spam" then :spam
    else
                                flash[:alert] = "Invalid action."
                                redirect_to trained_messages_path(params.except(:commit, :trained_message_ids, :authenticity_token, :controller, :action).to_unsafe_h)
                                return
    end

    messages.update_all(message_type: new_message_type_symbol, marked_by: TrainedMessage.marked_bies[:admin_dashboard], updated_at: Time.current)

    # Update all messages to the same message type if they have same
    # message hash
    message_hashes_to_sync = messages.pluck(:message_hash).uniq
    message_hashes_to_sync.each do |hash|
      MessageTypeSyncJob.perform_later(hash, new_message_type_symbol)
    end

    messages.each do |message|
      if message.spam? || message.ham?
        BatchProcessor.add_to_batch(
          "classifier_training_batch_key",
          "ClassifierTrainerJob",
          message,
          {},
          batch_size: 500,
          batch_window: 10.minutes
        )
      end
    end

    message_type_name = new_message_type_symbol.to_s
    flash[:notice] = "Successfully marked #{update_count} messages as #{message_type_name}"
    redirect_to trained_messages_path(params.except(:commit, :trained_message_ids, :authenticity_token, :controller, :action).to_unsafe_h)
  end

  # POST /trained_messages or /trained_messages.json
  def create
    @trained_message = TrainedMessage.new(trained_message_params)
    @trained_message.marked_by = :admin_dashboard

    respond_to do |format|
      if @trained_message.save
        format.html { redirect_to @trained_message, notice: "Trained message was successfully created." }
        format.json { render :show, status: :created, location: @trained_message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trained_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trained_messages/1 or /trained_messages/1.json
  def update
    # When updating through the admin dashboard, mark as admin_dashboard
    @trained_message.marked_by = :admin_dashboard if @trained_message.changed?

    respond_to do |format|
      if @trained_message.update(trained_message_params)
        format.html { redirect_to @trained_message, notice: "Trained message was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @trained_message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trained_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trained_messages/1 or /trained_messages/1.json
  def destroy
    @trained_message.destroy!
    return_url = params[:return_url] || trained_messages_path

    respond_to do |format|
      format.html { redirect_to return_url, notice: "Trained message was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_trained_message
    @trained_message = TrainedMessage.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def trained_message_params
    params.require(:trained_message).permit(:group_id, :message, :message_type, :sender_chat_id, :sender_user_name, :group_name, :training_target, :marked_by)
  end

  def index_params
    params.permit(:search, :message_type, :training_target, :group_name, :source, :marked_by, :per_page, :sort, :direction, :page)
  end

  helper_method :index_params
end

app/helpers/trained_messages_helper.rb
module TrainedMessagesHelper
  def message_type_classes(message_type)
    case message_type
    when "spam"
      "bg-red-100 text-red-800"
    when "ham"
      "bg-green-100 text-green-800"
    when "maybe_spam"
      "bg-orange-100 text-orange-800"
    when "maybe_ham"
      "bg-lime-100 text-lime-800"
    when "untrained"
      "bg-gray-100 text-gray-800"
    else
      "bg-gray-100 text-gray-800"
    end
  end

  def training_target_classes(training_target)
    case training_target
    when "message_content"
      "bg-blue-100 text-blue-800"
    when "user_name"
      "bg-purple-100 text-purple-800"
    else
      "bg-yellow-100 text-yellow-800"
    end
  end
end

app/views/trained_messages/_form.html.erb
<%= form_with(model: trained_message, class: "contents") do |form| %>
  <% if trained_message.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(trained_message.errors.count, "error") %> prohibited this trained_message from being saved:</h2>

      <ul class="list-disc ml-6">
        <% trained_message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :group_id %>
    <%= form.number_field :group_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": trained_message.errors[:group_id].none?, "border-red-400 focus:outline-red-600": trained_message.errors[:group_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :message %>
    <%= form.textarea :message, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": trained_message.errors[:message].none?, "border-red-400 focus:outline-red-600": trained_message.errors[:message].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :message_type %>
    <%= form.select :message_type, 
          options_for_select([['Spam', 'spam'], ['Ham', 'ham'], ['Untrained', 'untrained']], @trained_message.message_type), 
          { prompt: 'Select message type' },
       { class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": trained_message.errors[:message_type].none?, "border-red-400 focus:outline-red-600": trained_message.errors[:message_type].any?}] } %>
  </div>

  <div class="my-5">
    <%= form.label :training_target %>
    <%= form.select :training_target, 
          options_for_select([['Message Content', 'message_content'], ['User name', 'user_name']], @trained_message.training_target), 
          { prompt: 'Select training target' },
       { class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": trained_message.errors[:training_target].none?, "border-red-400 focus:outline-red-600": trained_message.errors[:training_target].any?}] } %>
  </div>

  <div class="my-5">
    <%= form.label :source %>
    <%= form.select :source,
          options_for_select([['Chat', 'chat'], ['Feedspam Command', 'feedspam_command'], ['Import', 'import']], @trained_message.source),
          { prompt: 'Select source' },
       { class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": trained_message.errors[:source].none?, "border-red-400 focus:outline-red-600": trained_message.errors[:source].any?}] } %>
  </div>

  <div class="my-5">
      <%= form.label :marked_by %>
      <%= form.select :marked_by,
       options_for_select([['Group Admin', 'group_admin'], ['Admin Dashboard', 'admin_dashboard'], ['Auto Sync', 'auto_sync'], ['Not Marked Yet', 'not_marked_yet']], @trained_message.marked_by),
       { prompt: 'Select who marked this' },
       { class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": trained_message.errors[:marked_by].none?, "border-red-400 focus:outline-red-600": trained_message.errors[:marked_by].any?}] } %>
  </div>

  <div class="my-5">
    <%= form.label :sender_chat_id %>
    <%= form.number_field :sender_chat_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": trained_message.errors[:sender_chat_id].none?, "border-red-400 focus:outline-red-600": trained_message.errors[:sender_chat_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/trained_messages/_trained_message.html.erb
<div id="<%= dom_id trained_message %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Group:</strong>
    <%= trained_message.group_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Group name:</strong>
    <%= trained_message.group_name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Message:</strong>
    <%= trained_message.message %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Message type:</strong>
    <%= trained_message.message_type %>
  </div>

  <div>
    <strong class="block font-medium mb-1">Telegram Message Id:</strong>
    <%= trained_message.message_id %>
  </div>

  <div>
    <strong class="block font-medium mb-1">Message Hash:</strong>
    <%= trained_message.message_hash %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Training target:</strong>
    <%= trained_message.training_target %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Source:</strong>
    <%= trained_message.source %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Marked by:</strong>
    <%= trained_message.marked_by&.humanize || 'Unknown' %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Sender chat id:</strong>
    <%= trained_message.sender_chat_id %>
  </div>

  <div>
    <strong class="block font-medium mb-1">Sender user name:</strong>
    <%= trained_message.sender_user_name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Created at:</strong>
    <%= trained_message.created_at.strftime("%Y-%m-%d %H:%M") %>
  </div>
</div>

app/views/trained_messages/edit.html.erb
<% content_for :title, "Editing trained message" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing trained message</h1>

  <%= render "form", trained_message: @trained_message %>

  <%= link_to "Show this trained message", @trained_message, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to trained messages", trained_messages_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/trained_messages/new.html.erb
<% content_for :title, "New trained message" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New trained message</h1>

  <%= render "form", trained_message: @trained_message %>

  <%= link_to "Back to trained messages", trained_messages_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/trained_messages/show.html.erb
<% content_for :title, "Showing trained message" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing trained message</h1>

  <%= render @trained_message %>

  <%= link_to "Edit this trained message", edit_trained_message_path(@trained_message), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to trained messages", trained_messages_path(index_params), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this trained message", @trained_message, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" }, params: { return_url: params[:return_url] || trained_messages_path(index_params) } %>
</div>